### PR TITLE
ROGER-798: Added san-mount-staging , san-mount-prod to collectd templates

### PR DESCRIPTION
**Pull request by 04msambit**
@jordmoz : Please have a look at the changes

Made changes to collectd.conf.j2 files to add san-mount-prod and san-mount-staging.

Verified that the new mount points are mounted successfully by setting up monitoring on  localmesos01.

### CODE REVIEW

**Comment by jordmoz** [comment]
LGTM

**Comment by ankanm** [comment]
I'm wondering why do we have `/san_mount` and `/data/san_mount`. Aren't they the same?
@jordmoz

**Comment by ankanm** [comment]
If they are the same we could remove the following -

```
MountPoint "/san-mount"
MountPoint "/san-mount-prod"
MountPoint "/san-mount-staging"
```

**Comment by jordmoz** [comment]
Good point, works for me.  I'd prefer we keep the /data/san-\* mounts though

**Comment by 04msambit** [comment]
Removed /san-mount , /san-mount-staging and /san-mount-prod.

**Comment by ankanm** [comment]
LGTM

**Pull request merged**
