### PR TITLE
ROGER-743: Monitor bind via collectd.

### PR DESCRIPTION
**Pull request by jordmoz**

### CODE REVIEW

**Comment by ankanm** [comment]
What about masters? Will this cause issues when bind is not set up?

**Comment by jordmoz** [comment]
I don't want to put this on the masters quite yet.  I don't think they have a very high query rate, and because they are important infrastructure I want to take my time with them.

**Comment by ankanm** [comment]
I know. My point is that this configuration is for master & slave. So, is that not going to cause problems?

**Comment by ankanm** [comment]
So, you may need to add a condition.

**Comment by jordmoz** [comment]
It is already in the `{% if is_in_slaves is defined %}` section, so it's slave only.  You may need to expand the diff.

**Comment by ankanm** [comment]
So, as discussed let's use something like `enable_bind_monitoring` variable and set it for slaves (in the Moz environments.) So, by default it's not enabled (which is what we want for roger-mesos local and open source installs.)

**Comment by jordmoz** [comment]
Updated with the variable. Please look again.

**Comment by jordmoz** [comment]
This is up and running on dev and stage so I'm going to commit it as I don't want configs live but not in Git.  Further comments will go in another PR.

**Pull request merged**
